"""latest migration

Revision ID: 1bfa3e87206a
Revises: 79c40b503f16
Create Date: 2023-06-24 11:39:14.012916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfa3e87206a'
down_revision = '79c40b503f16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
