"""Initial migration

Revision ID: 2b4733e4a686
Revises: f43f2841ad1f
Create Date: 2023-06-11 10:53:19.898098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4733e4a686'
down_revision = 'f43f2841ad1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'date_added')
    # ### end Alembic commands ###
