"""latest migration

Revision ID: 79c40b503f16
Revises: 8ec8591e2bcc
Create Date: 2023-06-23 21:41:19.000662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c40b503f16'
down_revision = '8ec8591e2bcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_blog_id_fkey', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key('tags_blog_id_fkey', 'tags', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###
