"""third iterations

Revision ID: f43f2841ad1f
Revises: 3df8d60b57bc
Create Date: 2023-06-09 20:50:05.497585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43f2841ad1f'
down_revision = '3df8d60b57bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('image', sa.String(), nullable=True))
    op.add_column('blogs', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=False)
    op.create_index(op.f('ix_blogs_title'), 'blogs', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_title'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_column('blogs', 'description')
    op.drop_column('blogs', 'image')
    # ### end Alembic commands ###
